git:
  paging:
    colorArg: always
    pager: delta

customCommands:
  - key: "B"
    description: "Commitizen Tag Bump"
    context: "tags"
    loadingText: "Tagging ..."
    command: "cz bump -s --increment {{index .PromptResponses 0}}"
    prompts:
      - type: "menu"
        title: "Semver"
        options:
          - value: "PATCH"
          - value: "MINOR"
          - value: "MAJOR"
  - key: "z"
    command: "git cz c"
    description: "Commit with Commitizen no sign"
    context: "files"
    loadingText: "Opening commitizen commit tool"
    subprocess: true
  - key: "Z"
    command: "git cz c -s"
    description: "Commit with Commitizen Signed"
    context: "files"
    loadingText: "Opening commitizen commit tool"
    subprocess: true
  - key: "C"
    command: "cz ch"
    description: "Update/Generate Changelog"
    context: "tags"
    loadingText: "Updating Changelog"

theme:
  lightTheme: false
  activeBorderColor:
    - "#a6e3a1" # Green
    - bold
  inactiveBorderColor:
    - "#cdd6f4" # Text
  optionsTextColor:
    - "#89b4fa" # Blue
  selectedLineBgColor:
    - "#313244" # Surface0
  selectedRangeBgColor:
    - "#313244" # Surface0
  cherryPickedCommitBgColor:
    - "#94e2d5" # Teal
  cherryPickedCommitFgColor:
    - "#89b4fa" # Blue
  unstagedChangesColor:
    - red       # Red
